// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkoiuyaqlzsmbopyrini.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrb2l1eWFxbHpzbWJvcHlyaW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODQwMjEsImV4cCI6MjA3MDM2MDAyMX0.Rau5A3rjANPUO0a4U3rC-Np6mBPbhZx5Hxg_-yVbnzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});